name: FinalChat
version: 1.0.7
author: EverNife
main: br.com.finalcraft.finalchat.FinalChat
depend: [ EverNifeCore ]
softdepend: [ PlaceholderAPI, Factions, Essentials ]

commands:
  tell:
    description: EverNifeFancyChat Tell Command
    usage: /<command>
    aliases: [whispper,t,w,msg,private,r]
  inchannel:
    description: EverNifeFancyChat InChannel Command
    usage: /<command>
  muteall:
    description: EverNifeFancyChat Mute Command
    usage: /<command>