name: EverNifeFancyChat
version: 1.0.2
author: EverNife
main: br.com.finalcraft.fancychat.EverNifeFancyChat
softdepend: [ PlaceholderAPI, Factions]

commands:
  chat:
    description: EverNifeFancyChat Main Command
    usage: /<command>
    aliases: [fancychat,fchat]
  tell:
    description: EverNifeFancyChat Tell Command
    usage: /<command>
    aliases: [inChannel,t,w,msg,private,r]
  channellock:
    description: EverNifeFancyChat InChannel Command
    usage: /<command>
    aliases: [ch,channel,lock,msg,private,r]
  inchannel:
    description: EverNifeFancyChat InChannel Command
    usage: /<command>
  mute:
    description: EverNifeFancyChat Mute Command
    usage: /<command>
    aliases: [tempmute,chatmute,silence]
permissions:
  fancychat.command.reload:
    description: Allow user to reload Config (reload all tags, channels, etc).
    default: false
  fancychat.command.mute:
    description: Allow user to mute others Players.
    default: false
  fancychat.command.spy:
    description: Allow user to see others chat (pms and local)
    default: false
  fancychat.chat.color:
    description: Allow user to use color codes on chat.
    default: false
  fancychat.chat.staff:
    description: A user with this message can't be muted and will be able to speak when Global channel is locked.
    default: false